[
    {
        "id": 1,
        "name": "赤崁樓",
        "district": "中西區",
        "category": "古蹟",
        "image_url": "https://picsum.photos/600/400?random=1",
        "description": "台南最具代表性的歷史古蹟之一，建於荷蘭統治時期。",
        "created_at": "2026-07-24 10:00:00",
    },
    {
        "id": 2,
        "name": "安平古堡",
        "district": "安平區",
        "category": "古蹟",
        "image_url": "https://picsum.photos/600/400?random=2",
        "description": "台灣第一座西式城堡，見證台南的歷史發展。",
        "created_at": "2026-07-24 10:05:00",
    },
    {
        "id": 3,
        "name": "神農街",
        "district": "中西區",
        "category": "熱門景點",
        "image_url": "https://picsum.photos/600/400?random=3",
        "description": "保存老屋街景，夜晚燈籠點亮後充滿復古氛圍。",
        "created_at": "2026-07-24 10:10:00",
    },
    {
        "id": 4,
        "name": "花園夜市",
        "district": "北區",
        "category": "美食",
        "image_url": "https://picsum.photos/600/400?random=4",
        "description": "台南知名夜市，各式小吃及遊戲攤位齊全。",
        "created_at": "2026-07-24 10:15:00",
    },
    {
        "id": 5,
        "name": "國華街",
        "district": "中西區",
        "category": "美食",
        "image_url": "https://picsum.photos/600/400?random=5",
        "description": "聚集台南經典小吃，是遊客必訪的美食街。",
        "created_at": "2026-07-24 10:20:00",
    },
    {
        "id": 6,
        "name": "四草綠色隧道",
        "district": "安南區",
        "category": "自然景觀",
        "image_url": "https://picsum.photos/600/400?random=6",
        "description": "搭船穿越紅樹林，被稱為台灣版亞馬遜河。",
        "created_at": "2026-07-24 10:25:00",
    },
    {
        "id": 7,
        "name": "奇美博物館",
        "district": "仁德區",
        "category": "熱門景點",
        "image_url": "https://picsum.photos/600/400?random=7",
        "description": "收藏大量藝術品、兵器及樂器，是台南熱門景點。",
        "created_at": "2026-07-24 10:30:00",
    },
    {
        "id": 8,
        "name": "漁光島",
        "district": "安平區",
        "category": "自然景觀",
        "image_url": "https://picsum.photos/600/400?random=8",
        "description": "擁有沙灘與夕陽景色，是近年熱門拍照景點。",
        "created_at": "2026-07-24 10:35:00",
    },
    {
        "id": 9,
        "name": "林百貨",
        "district": "中西區",
        "category": "熱門景點",
        "image_url": "https://picsum.photos/600/400?random=9",
        "description": "日治時期百貨公司重新活化，融合歷史與文創。",
        "created_at": "2026-07-24 10:40:00",
    },
    {
        "id": 10,
        "name": "台南孔廟",
        "district": "中西區",
        "category": "古蹟",
        "image_url": "https://picsum.photos/600/400?random=10",
        "description": "全台第一座孔廟，也是重要的文化教育景點。",
        "created_at": "2026-07-24 10:45:00",
    },
]
