[
    {
        "id": 1,
        "name": "赤崁樓",
        "district": "中西區",
        "category": "古蹟",
        "image_url": "https://picsum.photos/600/400?random=1",
        "description": "台南最具代表性的歷史古蹟之一，建於荷蘭統治時期。",
        "created_at": "2026-07-24 10:00:00",
    },
    {
        "id": 2,
        "name": "安平古堡",
        "district": "安平區",
        "category": "古蹟",
        "image_url": "https://picsum.photos/600/400?random=2",
        "description": "台灣第一座西式城堡，見證台南的歷史發展。",
        "created_at": "2026-07-24 10:05:00",
    },
    {
        "id": 3,
        "name": "神農街",
        "district": "中西區",
        "category": "熱門景點",
        "image_url": "https://picsum.photos/600/400?random=3",
        "description": "保存老屋街景，夜晚燈籠點亮後充滿復古氛圍。",
        "created_at": "2026-07-24 10:10:00",
    },
    {
        "id": 4,
        "name": "花園夜市",
        "district": "北區",
        "category": "美食",
        "image_url": "https://picsum.photos/600/400?random=4",
        "description": "台南知名夜市，各式小吃及遊戲攤位齊全。",
        "created_at": "2026-07-24 10:15:00",
    },
    {
        "id": 5,
        "name": "國華街",
        "district": "中西區",
        "category": "美食",
        "image_url": "https://picsum.photos/600/400?random=5",
        "description": "聚集台南經典小吃，是遊客必訪的美食街。",
        "created_at": "2026-07-24 10:20:00",
    },
    {
        "id": 6,
        "name": "四草綠色隧道",
        "district": "安南區",
        "category": "自然景觀",
        "image_url": "https://picsum.photos/600/400?random=6",
        "description": "搭船穿越紅樹林，被稱為台灣版亞馬遜河。",
        "created_at": "2026-07-24 10:25:00",
    },
    {
        "id": 7,
        "name": "奇美博物館",
        "district": "仁德區",
        "category": "熱門景點",
        "image_url": "https://picsum.photos/600/400?random=7",
        "description": "收藏大量藝術品、兵器及樂器，是台南熱門景點。",
        "created_at": "2026-07-24 10:30:00",
    },
    {
        "id": 8,
        "name": "漁光島",
        "district": "安平區",
        "category": "自然景觀",
        "image_url": "https://picsum.photos/600/400?random=8",
        "description": "擁有沙灘與夕陽景色，是近年熱門拍照景點。",
        "created_at": "2026-07-24 10:35:00",
    },
    {
        "id": 9,
        "name": "林百貨",
        "district": "中西區",
        "category": "熱門景點",
        "image_url": "https://picsum.photos/600/400?random=9",
        "description": "日治時期百貨公司重新活化，融合歷史與文創。",
        "created_at": "2026-07-24 10:40:00",
    },
    {
        "id": 10,
        "name": "台南孔廟",
        "district": "中西區",
        "category": "古蹟",
        "image_url": "https://picsum.photos/600/400?random=10",
        "description": "全台第一座孔廟，也是重要的文化教育景點。",
        "created_at": "2026-07-24 10:45:00",
    },
    {
        "id": 11,
        "name": "藍晒圖文創園區",
        "district": "南區",
        "category": "熱門景點",
        "image_url": "https://picsum.photos/600/400?random=11",
        "description": "由舊司法宿舍改建而成，結合文創商店與藝術裝置。",
        "created_at": "2026-07-24 10:50:00",
    },
    {
        "id": 12,
        "name": "億載金城",
        "district": "安平區",
        "category": "古蹟",
        "image_url": "https://picsum.photos/600/400?random=12",
        "description": "清朝時期興建的海防砲台，是重要的歷史文化資產。",
        "created_at": "2026-07-24 10:55:00",
    },
    {
        "id": 13,
        "name": "井仔腳瓦盤鹽田",
        "district": "北門區",
        "category": "自然景觀",
        "image_url": "https://picsum.photos/600/400?random=13",
        "description": "台灣現存最古老的瓦盤鹽田，可體驗曬鹽文化。",
        "created_at": "2026-07-24 11:00:00",
    },
    {
        "id": 15,
        "name": "阿堂鹹粥",
        "district": "中西區",
        "category": "美食",
        "image_url": "https://picsum.photos/600/400?random=15",
        "description": "台南知名鹹粥名店，以新鮮海鮮和虱目魚料理聞名。",
        "created_at": "2026-07-24 11:10:00",
    },
    {
        "id": 16,
        "name": "度小月擔仔麵",
        "district": "中西區",
        "category": "美食",
        "image_url": "https://picsum.photos/600/400?random=16",
        "description": "創立超過百年的老店，是台南代表性小吃之一。",
        "created_at": "2026-07-24 11:15:00",
    },
    {
        "id": 17,
        "name": "十鼓仁糖文創園區",
        "district": "仁德區",
        "category": "熱門景點",
        "image_url": "https://picsum.photos/600/400?random=17",
        "description": "結合糖廠歷史、鼓樂文化與高空設施的文創園區。",
        "created_at": "2026-07-24 11:20:00",
    },
    {
        "id": 18,
        "name": "台江國家公園",
        "district": "安南區",
        "category": "自然景觀",
        "image_url": "https://picsum.photos/600/400?random=18",
        "description": "擁有豐富濕地生態與候鳥，是生態旅遊的重要景點。",
        "created_at": "2026-07-24 11:25:00",
    },
    {
        "id": 19,
        "name": "延平郡王祠",
        "district": "中西區",
        "category": "古蹟",
        "image_url": "https://picsum.photos/600/400?random=19",
        "description": "為紀念鄭成功而建，是台南著名歷史古蹟。",
        "created_at": "2026-07-24 11:30:00",
    },
    {
        "id": 20,
        "name": "安平樹屋",
        "district": "安平區",
        "category": "熱門景點",
        "image_url": "https://picsum.photos/600/400?random=20",
        "description": "榕樹與舊倉庫交織而成的特殊景觀，是安平代表景點之一。",
        "created_at": "2026-07-24 11:35:00",
    },
    {
        "id": 21,
        "name": "富盛號碗粿",
        "district": "中西區",
        "category": "美食",
        "image_url": "https://picsum.photos/600/400?random=21",
        "description": "國華街上的百年名店，招牌碗粿與土魠魚羹口感鮮甜，是排隊必訪的老字號小吃。",
        "created_at": "2026-07-25 09:00:00",
    },
    {
        "id": 22,
        "name": "金得春捲",
        "district": "中西區",
        "category": "美食",
        "image_url": "https://picsum.photos/600/400?random=22",
        "description": "位於民族路的人氣春捲攤，現包現吃、內餡豐富紮實，是府城傳統小吃代表之一。",
        "created_at": "2026-07-25 09:05:00",
    },
    {
        "id": 23,
        "name": "阿財牛肉湯",
        "district": "安平區",
        "category": "美食",
        "image_url": "https://picsum.photos/600/400?random=23",
        "description": "安平老街上的知名牛肉湯店，現切溫體牛肉搭配濃郁湯頭，是在地人推薦的宵夜首選。",
        "created_at": "2026-07-25 09:10:00",
    },
    {
        "id": 24,
        "name": "矮仔成蝦仁飯",
        "district": "中西區",
        "category": "美食",
        "image_url": "https://picsum.photos/600/400?random=24",
        "description": "台南百年老店，鮮甜蝦仁鋪滿白飯上，是府城米食小吃的代表之一。",
        "created_at": "2026-07-25 09:15:00",
    },
    {
        "id": 25,
        "name": "石精臼蚵仔煎",
        "district": "中西區",
        "category": "美食",
        "image_url": "https://picsum.photos/600/400?random=25",
        "description": "西門路商圈的老字號蚵仔煎攤，酥脆外皮包裹肥美蚵仔，深受在地饕客喜愛。",
        "created_at": "2026-07-25 09:20:00",
    },
    {
        "id": 26,
        "name": "小公園擔仔麵",
        "district": "中西區",
        "category": "美食",
        "image_url": "https://picsum.photos/600/400?random=26",
        "description": "飄香超過七十年的擔仔麵老店，以蝦頭高湯與肉燥聞名，是府城經典小吃之一。",
        "created_at": "2026-07-25 09:25:00",
    },
    {
        "id": 27,
        "name": "王氏魚皮",
        "district": "安平區",
        "category": "美食",
        "image_url": "https://picsum.photos/600/400?random=27",
        "description": "安平在地虱目魚料理專賣店，魚皮軟嫩鮮香、價格親民，是安平巷弄美食代表。",
        "created_at": "2026-07-25 09:30:00",
    },
    {
        "id": 28,
        "name": "莉莉水果店",
        "district": "中西區",
        "category": "美食",
        "image_url": "https://picsum.photos/600/400?random=28",
        "description": "開業超過六十年的老字號水果店，以當季新鮮水果冰品聞名，是消暑必訪名店。",
        "created_at": "2026-07-25 09:35:00",
    },
    {
        "id": 29,
        "name": "台南美術館二館",
        "district": "中西區",
        "category": "熱門景點",
        "image_url": "https://picsum.photos/600/400?random=29",
        "description": "由日台建築師共同打造的幾何白色建築，展出當代藝術作品，是近年最受歡迎的拍照景點之一。",
        "created_at": "2026-07-25 09:40:00",
    },
    {
        "id": 30,
        "name": "觀夕平台",
        "district": "安平區",
        "category": "熱門景點",
        "image_url": "https://picsum.photos/600/400?random=30",
        "description": "安平海堤上的觀景平台，可欣賞夕陽與海景，傍晚時分景色浪漫，是熱門的賞景地點。",
        "created_at": "2026-07-25 09:45:00",
    },
    {
        "id": 31,
        "name": "台南港濱歷史公園",
        "district": "安平區",
        "category": "熱門景點",
        "image_url": "image/101.jpg",
        "description": "鄰近安平的濱海公園，園內有大型鯨魚裝置藝術「大魚的祝福」，環境優美適合散步拍照。",
        "created_at": "2026-07-25 09:50:00",
    },
    {
        "id": 32,
        "name": "河樂廣場",
        "district": "中西區",
        "category": "熱門景點",
        "image_url": "https://picsum.photos/600/400?random=32",
        "description": "由舊商場改建而成的親水廣場，提供市中心免費戲水空間，是親子休閒的熱門去處。",
        "created_at": "2026-07-25 09:55:00",
    },
    {
        "id": 33,
        "name": "國立台灣文學館",
        "district": "中西區",
        "category": "熱門景點",
        "image_url": "https://picsum.photos/600/400?random=33",
        "description": "全台第一座文學博物館，建築融合西洋歷史風格，館內典藏豐富文學史料，也是免費參觀的知名景點。",
        "created_at": "2026-07-25 10:00:00",
    },
    {
        "id": 34,
        "name": "南瀛天文館",
        "district": "大內區",
        "category": "熱門景點",
        "image_url": "https://picsum.photos/600/400?random=34",
        "description": "結合天文知識與科幻場景的展館，設有模擬太空船體驗設施，是熱門的親子景點。",
        "created_at": "2026-07-25 10:05:00",
    },
    {
        "id": 35,
        "name": "祀典大天后宮",
        "district": "中西區",
        "category": "古蹟",
        "image_url": "https://picsum.photos/600/400?random=35",
        "description": "台灣第一座官建媽祖廟，前身為明鄭寧靖王府，保存眾多古匾與清代石碑，是重要的國定古蹟。",
        "created_at": "2026-07-25 10:10:00",
    },
    {
        "id": 36,
        "name": "祀典武廟",
        "district": "中西區",
        "category": "古蹟",
        "image_url": "https://picsum.photos/600/400?random=36",
        "description": "主祀關聖帝君的古廟，建築格局完整，與大天后宮相鄰，是府城信仰與歷史的重要地標。",
        "created_at": "2026-07-25 10:15:00",
    },
    {
        "id": 37,
        "name": "將軍鹽田生命之樹",
        "district": "將軍區",
        "category": "自然景觀",
        "image_url": "https://picsum.photos/600/400?random=37",
        "description": "位於扇形鹽田中的裝置藝術作品，夕陽時分鹽田倒映霞光，呈現獨特的鹽業地景之美。",
        "created_at": "2026-07-25 10:20:00",
    },
    {
        "id": 38,
        "name": "德元埤荷蘭村",
        "district": "柳營區",
        "category": "自然景觀",
        "image_url": "https://picsum.photos/600/400?random=38",
        "description": "佔地廣闊的免費景點，園內有風車與草原造景，充滿荷蘭風情，適合親子踏青。",
        "created_at": "2026-07-25 10:25:00",
    },
]
