attraction_detail_data = [
    {
        "attraction_id": 2,
        "opening_hours": "08:30-21:30",
        "address": "台南市中西區民族路二段212號",
        "ticket_info": "全票70元、半票35元（台南市市民憑身分證免費）",
        "official_url": "https://historic.tainan.gov.tw",
        "tips": "可參加免費定時導覽解說，時間為上午10:00、11:00，下午13:30、14:30、15:30。",
    },
    {
        "attraction_id": 3,
        "opening_hours": "08:30-17:30",
        "address": "台南市安平區國勝路82號",
        "ticket_info": "全票70元、半票35元（台南市市民憑身分證免費）",
        "official_url": "https://historic.tainan.gov.tw",
        "tips": "可登上瞭望台俯瞰安平全景，出口正對面即是開台天后宮，適合順遊。",
    },
    {
        "attraction_id": 4,
        "opening_hours": "24小時開放（店家營業時間各異，多集中在11:00~22:00）",
        "address": "台南市中西區神農街",
        "ticket_info": "免費",
        "official_url": None,
        "tips": "傍晚點燈後最有氛圍，白天多數店家未開門，建議晚上前往。",
    },
    {
        "attraction_id": 20,
        "opening_hours": "每週四、五、六、日 17:00-00:00",
        "address": "台南市北區海安路三段533號",
        "ticket_info": "免費入場",
        "official_url": None,
        "tips": "假日人潮眾多，建議提早到場並避開晚間8點後的用餐尖峰。",
    },
    {
        "attraction_id": 6,
        "opening_hours": "全天開放，各店家營業時間不同（多集中在早上7點至晚上8點）",
        "address": "台南市中西區國華街",
        "ticket_info": "免費",
        "official_url": None,
        "tips": "知名小吃多集中在二段、三段（永樂市場周邊），建議避開中午用餐尖峰。",
    },
    {
        "attraction_id": 8,
        "opening_hours": "09:30-17:30（週三公休、除夕休館）",
        "address": "台南市仁德區文華路二段66號",
        "ticket_info": "全票200元、優待票150元（台南市民及在台南就學學生持證免費）",
        "official_url": "https://www.chimeimuseum.org",
        "tips": "戶外園區開放至18:30，建議預留2小時以上參觀時間。",
    },
    {
        "attraction_id": 9,
        "opening_hours": "24小時開放",
        "address": "台南市安平區漁光路",
        "ticket_info": "免費",
        "official_url": None,
        "tips": "夕陽時段人潮最多，海域禁止戲水游泳，請留意自身安全。",
    },
    {
        "attraction_id": 10,
        "opening_hours": "11:00-21:00",
        "address": "台南市中西區忠義路二段63號",
        "ticket_info": "免費參觀（商店消費另計）",
        "official_url": "http://www.hayashi.com.tw/",
        "tips": "頂樓神社「末廣社」與二戰彈孔遺跡是必看亮點，也是全台唯一設有神社的百貨。",
    },
    {
        "attraction_id": 13,
        "opening_hours": "園區08:30-17:30（免費）；以成書院09:00-17:00",
        "address": "台南市中西區南門路2號",
        "ticket_info": "免費",
        "official_url": "https://www.tn-confucius.org.tw",
        "tips": "建議上午前往人潮較少，可順遊對面的府中街。",
    },
    {
        "attraction_id": 5,
        "opening_hours": "10:00-21:00（週二公休）",
        "address": "台南市南區西門路一段689巷12號",
        "ticket_info": "免費",
        "official_url": None,
        "tips": "夜晚點燈後拍照效果最佳，園內3D藍晒圖為必拍地標。",
    },
    {
        "attraction_id": 12,
        "opening_hours": "08:30-17:30",
        "address": "台南市安平區光州路3號",
        "ticket_info": "全票70元、半票35元（台南市市民免費）",
        "official_url": "https://historic.tainan.gov.tw",
        "tips": "護城河可租天鵝船遊湖，適合安排半天行程。",
    },
    {
        "attraction_id": 14,
        "opening_hours": "24小時開放（遊客中心09:00-17:30）",
        "address": "台南市北門區復育鹽田西南郊",
        "ticket_info": "免費",
        "official_url": None,
        "tips": "以夕陽時段拍照最美；場域曾因風災部分整修，建議先查詢粉專最新開放狀況。",
    },
    {
        "attraction_id": 16,
        "opening_hours": "05:00-12:30（賣完為止，週二公休）",
        "address": "台南市中西區西門路一段728號",
        "ticket_info": None,
        "official_url": None,
        "tips": "假日人潮多，建議平日或提早前往，避免向晚售罄。",
    },
    {
        "attraction_id": 11,
        "opening_hours": "11:00-20:30（20:00最後點餐）",
        "address": "台南市中西區中正路16號",
        "ticket_info": None,
        "official_url": "https://noodle1895.com/",
        "tips": "招牌擔仔麵份量偏小，建議搭配其他小菜一起點才吃得飽。",
    },
    {
        "attraction_id": 15,
        "opening_hours": "平日10:00-20:20；假日09:30-20:20（依季節與活動略有調整）",
        "address": "台南市仁德區文華路二段326號",
        "ticket_info": "全票約490元（另有學生、市民、敬老兒童等優惠票，依官網公告為準）",
        "official_url": "https://tendrum.com.tw/",
        "tips": "夜間點燈後氛圍與白天截然不同，可安排傍晚入園順遊至晚上。",
    },
    {
        "attraction_id": 17,
        "opening_hours": "遊客中心09:00-17:00（週一休館）；戶外園區全天開放",
        "address": "台南市安南區四草大道118號",
        "ticket_info": "免費",
        "official_url": "https://www.tjnp.gov.tw",
        "tips": "戶外定時導覽時間為10:00、11:00、14:30、15:30，每場約20分鐘，現場免費報名。",
    },
    {
        "attraction_id": 18,
        "opening_hours": "08:30-17:30",
        "address": "台南市中西區開山路152號",
        "ticket_info": "免費",
        "official_url": None,
        "tips": "祠內四扇門神繪製成藍眼睛外國人造型，是為感念鄭成功而設計，相當特別。",
    },
    {
        "attraction_id": 19,
        "opening_hours": "08:30-17:30",
        "address": "台南市安平區古堡街108號旁",
        "ticket_info": "全票70元、半票35元（台南市市民免費）",
        "official_url": "https://historic.tainan.gov.tw",
        "tips": "可一併參觀相鄰的德記洋行與朱玖瑩故居，一張門票三個景點。",
    },
    {
        "attraction_id": 22,
        "opening_hours": "07:00-17:30（週四公休）",
        "address": "台南市中西區民族路三段11號",
        "ticket_info": None,
        "official_url": None,
        "tips": "與金得春捲、阿松割包並列「國華街美食鐵三角」，可連著一起吃。",
    },
    {
        "attraction_id": 23,
        "opening_hours": "07:30-17:00（週二公休）",
        "address": "台南市中西區民族路三段19號",
        "ticket_info": None,
        "official_url": "http://www.kintoku.com/",
        "tips": "內餡多達10幾種食材，甜度可事先告知店家調整比例。",
    },
    {
        "attraction_id": 24,
        "opening_hours": "約11:30-22:00（依店家公告為準）",
        "address": "台南市安平區古堡街5號",
        "ticket_info": None,
        "official_url": None,
        "tips": "用餐環境較克難，假日中午常大排長龍，建議避開尖峰時段。",
    },
    {
        "attraction_id": 25,
        "opening_hours": "08:30-19:30（週二公休）",
        "address": "台南市中西區海安路一段66號",
        "ticket_info": None,
        "official_url": None,
        "tips": "招牌蝦仁飯曾入選2024年總統就職國宴菜色，是百年老店。",
    },
    {
        "attraction_id": 26,
        "opening_hours": "07:00-18:00",
        "address": "台南市中西區國華街三段182號",
        "ticket_info": None,
        "official_url": None,
        "tips": "推薦搭配店內招牌香菇飯湯一起享用，內用空間不大。",
    },
    {
        "attraction_id": 27,
        "opening_hours": "16:30-22:00（週二、三公休）",
        "address": "台南市中西區西門路二段321號",
        "ticket_info": None,
        "official_url": None,
        "tips": "70年老店，米其林必比登連續多年推薦，建議點湯麵品嚐蝦頭湯湯頭。",
    },
    {
        "attraction_id": 28,
        "opening_hours": "04:00-14:00（平日）／04:00-15:00（週六、日）",
        "address": "台南市安平區安平路612號",
        "ticket_info": None,
        "official_url": None,
        "tips": "早餐（6-8點）與午餐（11-13點）時段人潮最多，建議避開。",
    },
    {
        "attraction_id": 29,
        "opening_hours": "11:00-22:00（週三公休）",
        "address": "台南市中西區府前路一段199號",
        "ticket_info": None,
        "official_url": None,
        "tips": "近80年老字號冰果室，招牌綜合水果冰一次可吃到近十種當季水果。",
    },
    {
        "attraction_id": 30,
        "opening_hours": "10:00-18:00（週六延長至21:00，週一公休）",
        "address": "台南市中西區忠義路二段1號",
        "ticket_info": "全票約200元（常設展另計，一票可同遊一館與二館，依官網公告為準）",
        "official_url": "https://www.tnam.museum/",
        "tips": "戶外空間免費開放，鳳凰花意象的白色建築本身就是熱門拍照地標。",
    },
    {
        "attraction_id": 31,
        "opening_hours": "24小時開放",
        "address": "台南市安平區漁濱路",
        "ticket_info": "免費",
        "official_url": None,
        "tips": "夕陽時段最熱門，可順遊一旁的安平燈塔。",
    },
    {
        "attraction_id": 32,
        "opening_hours": "24小時開放（「大魚的祝福」夜間點燈18:00-22:00）",
        "address": "台南市安平區安億路",
        "ticket_info": "免費",
        "official_url": None,
        "tips": "「大魚的祝福」鯨魚裝置藝術是必拍地標，白天夜晚各有不同風貌。",
    },
    {
        "attraction_id": 33,
        "opening_hours": "09:00-22:00（週二公休）",
        "address": "台南市中西區中正路343-20號",
        "ticket_info": "免費",
        "official_url": None,
        "tips": "戲水池水深僅30公分，適合親子同遊，建議自備溯溪鞋避免滑倒。",
    },
    {
        "attraction_id": 34,
        "opening_hours": "週二至週日09:00-18:00（週一公休）",
        "address": "台南市中西區中正路1號",
        "ticket_info": "免費",
        "official_url": "https://www.nmtl.gov.tw/",
        "tips": "建築前身為1916年落成的日治時期台南州廳，本身即是國定古蹟。",
    },
    {
        "attraction_id": 35,
        "opening_hours": "週二至週日09:00-17:00（週一公休，週六夜間延長至21:00）",
        "address": "台南市大內區曲溪里34-2號",
        "ticket_info": "各館分開售票，天文展示館全票約80元、星象劇場3D全票約150元，戶外與觀測館免費（依官網公告為準）",
        "official_url": "https://taea.tn.edu.tw/",
        "tips": "週六夜間開放星空觀測活動，適合安排親子夜遊行程。",
    },
    {
        "attraction_id": 36,
        "opening_hours": "06:00-21:00",
        "address": "台南市中西區永福路二段227巷18號",
        "ticket_info": "免費",
        "official_url": "https://www.gtainanmazu.org.tw/",
        "tips": "後殿供奉月老公公，是許多人求姻緣的熱門地點。",
    },
    {
        "attraction_id": 37,
        "opening_hours": "09:00-20:00",
        "address": "台南市中西區永福路二段229號",
        "ticket_info": "免費",
        "official_url": None,
        "tips": "廟前朱紅色山牆長達66公尺、高5.5公尺，是台南最具代表性的街景之一。",
    },
    {
        "attraction_id": 38,
        "opening_hours": "24小時開放",
        "address": "台南市將軍區青鯤鯓扇形鹽田（扇鹽地景園區）",
        "ticket_info": "免費",
        "official_url": None,
        "tips": "建議傍晚前往，可拍到落日餘暉倒映在扇形鹽田上的畫面。",
    },
    {
        "attraction_id": 39,
        "opening_hours": "全天開放（風車運轉時間：平日13:00-16:00、假日10:00-16:00）",
        "address": "台南市柳營區神農里新厝100號",
        "ticket_info": "免費",
        "official_url": None,
        "tips": "園區內可露營、划獨木舟，適合安排半天以上的行程。",
    },
]
