[
    {
        "id": 1,
        "name": "赤崁樓",
        "district": "中西區",
        "category": "古蹟",
        "image_url": "https://picsum.photos/600/400?random=1",
        "description": "台南最具代表性的歷史古蹟之一，建於荷蘭統治時期。",
        "created_at": "2026-07-24 10:00:00",
    },
    {
        "id": 2,
        "name": "安平古堡",
        "district": "安平區",
        "category": "古蹟",
        "image_url": "https://picsum.photos/600/400?random=2",
        "description": "台灣第一座西式城堡，見證台南的歷史發展。",
        "created_at": "2026-07-24 10:05:00",
    },
    {
        "id": 3,
        "name": "神農街",
        "district": "中西區",
        "category": "熱門景點",
        "image_url": "https://picsum.photos/600/400?random=3",
        "description": "保存老屋街景，夜晚燈籠點亮後充滿復古氛圍。",
        "created_at": "2026-07-24 10:10:00",
    },
    {
        "id": 4,
        "name": "花園夜市",
        "district": "北區",
        "category": "美食",
        "image_url": "https://picsum.photos/600/400?random=4",
        "description": "台南知名夜市，各式小吃及遊戲攤位齊全。",
        "created_at": "2026-07-24 10:15:00",
    },
    {
        "id": 5,
        "name": "國華街",
        "district": "中西區",
        "category": "美食",
        "image_url": "https://picsum.photos/600/400?random=5",
        "description": "聚集台南經典小吃，是遊客必訪的美食街。",
        "created_at": "2026-07-24 10:20:00",
    },
    {
        "id": 6,
        "name": "四草綠色隧道",
        "district": "安南區",
        "category": "自然景觀",
        "image_url": "https://picsum.photos/600/400?random=6",
        "description": "搭船穿越紅樹林，被稱為台灣版亞馬遜河。",
        "created_at": "2026-07-24 10:25:00",
    },
    {
        "id": 7,
        "name": "奇美博物館",
        "district": "仁德區",
        "category": "熱門景點",
        "image_url": "https://picsum.photos/600/400?random=7",
        "description": "收藏大量藝術品、兵器及樂器，是台南熱門景點。",
        "created_at": "2026-07-24 10:30:00",
    },
    {
        "id": 8,
        "name": "漁光島",
        "district": "安平區",
        "category": "自然景觀",
        "image_url": "https://picsum.photos/600/400?random=8",
        "description": "擁有沙灘與夕陽景色，是近年熱門拍照景點。",
        "created_at": "2026-07-24 10:35:00",
    },
    {
        "id": 9,
        "name": "林百貨",
        "district": "中西區",
        "category": "熱門景點",
        "image_url": "https://picsum.photos/600/400?random=9",
        "description": "日治時期百貨公司重新活化，融合歷史與文創。",
        "created_at": "2026-07-24 10:40:00",
    },
    {
        "id": 10,
        "name": "台南孔廟",
        "district": "中西區",
        "category": "古蹟",
        "image_url": "https://picsum.photos/600/400?random=10",
        "description": "全台第一座孔廟，也是重要的文化教育景點。",
        "created_at": "2026-07-24 10:45:00",
    },
    {
        "id": 11,
        "name": "藍晒圖文創園區",
        "district": "南區",
        "category": "熱門景點",
        "image_url": "https://picsum.photos/600/400?random=11",
        "description": "由舊司法宿舍改建而成，結合文創商店與藝術裝置。",
        "created_at": "2026-07-24 10:50:00",
    },
    {
        "id": 12,
        "name": "億載金城",
        "district": "安平區",
        "category": "古蹟",
        "image_url": "https://picsum.photos/600/400?random=12",
        "description": "清朝時期興建的海防砲台，是重要的歷史文化資產。",
        "created_at": "2026-07-24 10:55:00",
    },
    {
        "id": 13,
        "name": "井仔腳瓦盤鹽田",
        "district": "北門區",
        "category": "自然景觀",
        "image_url": "https://picsum.photos/600/400?random=13",
        "description": "台灣現存最古老的瓦盤鹽田，可體驗曬鹽文化。",
        "created_at": "2026-07-24 11:00:00",
    },
    {
        "id": 14,
        "name": "七股鹽山",
        "district": "七股區",
        "category": "自然景觀",
        "image_url": "https://picsum.photos/600/400?random=14",
        "description": "以巨大鹽山聞名，是親子旅遊與拍照熱門景點。",
        "created_at": "2026-07-24 11:05:00",
    },
    {
        "id": 15,
        "name": "阿堂鹹粥",
        "district": "中西區",
        "category": "美食",
        "image_url": "https://picsum.photos/600/400?random=15",
        "description": "台南知名鹹粥名店，以新鮮海鮮和虱目魚料理聞名。",
        "created_at": "2026-07-24 11:10:00",
    },
    {
        "id": 16,
        "name": "度小月擔仔麵",
        "district": "中西區",
        "category": "美食",
        "image_url": "https://picsum.photos/600/400?random=16",
        "description": "創立超過百年的老店，是台南代表性小吃之一。",
        "created_at": "2026-07-24 11:15:00",
    },
    {
        "id": 17,
        "name": "十鼓仁糖文創園區",
        "district": "仁德區",
        "category": "熱門景點",
        "image_url": "https://picsum.photos/600/400?random=17",
        "description": "結合糖廠歷史、鼓樂文化與高空設施的文創園區。",
        "created_at": "2026-07-24 11:20:00",
    },
    {
        "id": 18,
        "name": "台江國家公園",
        "district": "安南區",
        "category": "自然景觀",
        "image_url": "https://picsum.photos/600/400?random=18",
        "description": "擁有豐富濕地生態與候鳥，是生態旅遊的重要景點。",
        "created_at": "2026-07-24 11:25:00",
    },
    {
        "id": 19,
        "name": "延平郡王祠",
        "district": "中西區",
        "category": "古蹟",
        "image_url": "https://picsum.photos/600/400?random=19",
        "description": "為紀念鄭成功而建，是台南著名歷史古蹟。",
        "created_at": "2026-07-24 11:30:00",
    },
    {
        "id": 20,
        "name": "安平樹屋",
        "district": "安平區",
        "category": "熱門景點",
        "image_url": "https://picsum.photos/600/400?random=20",
        "description": "榕樹與舊倉庫交織而成的特殊景觀，是安平代表景點之一。",
        "created_at": "2026-07-24 11:35:00",
    },
]
